-- Preserve retired numeric identities without rebuilding existing business tables.
CREATE TABLE entity_id_high_watermarks (
  table_name TEXT PRIMARY KEY CHECK (table_name IN ('customers','items','defect_reports','sales_work_orders','outsourcing_orders','contractors','work_logs','customer_visits','customer_frequent_items')),
  last_id INTEGER NOT NULL CHECK (last_id > 0 AND last_id <= 9007199254740991)
);
INSERT INTO entity_id_high_watermarks SELECT 'customers', MAX(CAST(entity_key AS INTEGER)) FROM audit_events WHERE entity_type='customer' AND entity_key NOT GLOB '*[^0-9]*' AND entity_key != '' HAVING MAX(CAST(entity_key AS INTEGER)) > 0;
CREATE TRIGGER retire_customers_identity AFTER DELETE ON customers BEGIN INSERT INTO entity_id_high_watermarks(table_name,last_id) VALUES('customers',OLD.id) ON CONFLICT(table_name) DO UPDATE SET last_id=MAX(last_id,excluded.last_id); END;
INSERT INTO entity_id_high_watermarks SELECT 'items', MAX(CAST(entity_key AS INTEGER)) FROM audit_events WHERE entity_type='item' AND entity_key NOT GLOB '*[^0-9]*' AND entity_key != '' HAVING MAX(CAST(entity_key AS INTEGER)) > 0;
CREATE TRIGGER retire_items_identity AFTER DELETE ON items BEGIN INSERT INTO entity_id_high_watermarks(table_name,last_id) VALUES('items',OLD.id) ON CONFLICT(table_name) DO UPDATE SET last_id=MAX(last_id,excluded.last_id); END;
INSERT INTO entity_id_high_watermarks SELECT 'defect_reports', MAX(CAST(entity_key AS INTEGER)) FROM audit_events WHERE entity_type='defect' AND entity_key NOT GLOB '*[^0-9]*' AND entity_key != '' HAVING MAX(CAST(entity_key AS INTEGER)) > 0;
CREATE TRIGGER retire_defect_reports_identity AFTER DELETE ON defect_reports BEGIN INSERT INTO entity_id_high_watermarks(table_name,last_id) VALUES('defect_reports',OLD.id) ON CONFLICT(table_name) DO UPDATE SET last_id=MAX(last_id,excluded.last_id); END;
INSERT INTO entity_id_high_watermarks SELECT 'sales_work_orders', MAX(CAST(entity_key AS INTEGER)) FROM audit_events WHERE entity_type='sales_work_order' AND entity_key NOT GLOB '*[^0-9]*' AND entity_key != '' HAVING MAX(CAST(entity_key AS INTEGER)) > 0;
CREATE TRIGGER retire_sales_work_orders_identity AFTER DELETE ON sales_work_orders BEGIN INSERT INTO entity_id_high_watermarks(table_name,last_id) VALUES('sales_work_orders',OLD.id) ON CONFLICT(table_name) DO UPDATE SET last_id=MAX(last_id,excluded.last_id); END;
INSERT INTO entity_id_high_watermarks SELECT 'outsourcing_orders', MAX(CAST(entity_key AS INTEGER)) FROM audit_events WHERE entity_type='outsourcing_order' AND entity_key NOT GLOB '*[^0-9]*' AND entity_key != '' HAVING MAX(CAST(entity_key AS INTEGER)) > 0;
CREATE TRIGGER retire_outsourcing_orders_identity AFTER DELETE ON outsourcing_orders BEGIN INSERT INTO entity_id_high_watermarks(table_name,last_id) VALUES('outsourcing_orders',OLD.id) ON CONFLICT(table_name) DO UPDATE SET last_id=MAX(last_id,excluded.last_id); END;
INSERT INTO entity_id_high_watermarks SELECT 'contractors', MAX(CAST(entity_key AS INTEGER)) FROM audit_events WHERE entity_type='contractor' AND entity_key NOT GLOB '*[^0-9]*' AND entity_key != '' HAVING MAX(CAST(entity_key AS INTEGER)) > 0;
CREATE TRIGGER retire_contractors_identity AFTER DELETE ON contractors BEGIN INSERT INTO entity_id_high_watermarks(table_name,last_id) VALUES('contractors',OLD.id) ON CONFLICT(table_name) DO UPDATE SET last_id=MAX(last_id,excluded.last_id); END;
INSERT INTO entity_id_high_watermarks SELECT 'work_logs', MAX(CAST(entity_key AS INTEGER)) FROM audit_events WHERE entity_type='work_log' AND entity_key NOT GLOB '*[^0-9]*' AND entity_key != '' HAVING MAX(CAST(entity_key AS INTEGER)) > 0;
CREATE TRIGGER retire_work_logs_identity AFTER DELETE ON work_logs BEGIN INSERT INTO entity_id_high_watermarks(table_name,last_id) VALUES('work_logs',OLD.id) ON CONFLICT(table_name) DO UPDATE SET last_id=MAX(last_id,excluded.last_id); END;
INSERT INTO entity_id_high_watermarks SELECT 'customer_visits', MAX(CAST(entity_key AS INTEGER)) FROM audit_events WHERE entity_type='customer_visit' AND entity_key NOT GLOB '*[^0-9]*' AND entity_key != '' HAVING MAX(CAST(entity_key AS INTEGER)) > 0;
CREATE TRIGGER retire_customer_visits_identity AFTER DELETE ON customer_visits BEGIN INSERT INTO entity_id_high_watermarks(table_name,last_id) VALUES('customer_visits',OLD.id) ON CONFLICT(table_name) DO UPDATE SET last_id=MAX(last_id,excluded.last_id); END;
CREATE TRIGGER retire_customer_frequent_items_identity AFTER DELETE ON customer_frequent_items BEGIN INSERT INTO entity_id_high_watermarks(table_name,last_id) VALUES('customer_frequent_items',OLD.id) ON CONFLICT(table_name) DO UPDATE SET last_id=MAX(last_id,excluded.last_id); END;
